//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Afip_TicketAcceso
    {
        public int id { get; set; }
        public string uniqueId { get; set; }
        public Nullable<System.DateTime> fecha_solicitud { get; set; }
        public Nullable<System.DateTime> fecha_expiracion { get; set; }
        public string servicio { get; set; }
        public string token { get; set; }
        public string sing { get; set; }
        public string url { get; set; }
        public Nullable<int> usuario { get; set; }
    }
}
