//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfipRegimen
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Concepto { get; set; }
        public Nullable<decimal> Aliri { get; set; }
        public Nullable<decimal> Alirni { get; set; }
        public Nullable<decimal> Minimo { get; set; }
        public Nullable<int> Imputacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
    }
}
