//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaSaldo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CajaSaldo()
        {
            this.Caja = new HashSet<Caja>();
        }
    
        public int Id { get; set; }
        public int NumeroCierrre { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal ImporteInicialPesos { get; set; }
        public Nullable<decimal> ImporteInicialDolares { get; set; }
        public decimal ImporteInicialCheques { get; set; }
        public decimal ImporteInicialTarjetas { get; set; }
        public decimal ImporteInicialDepositos { get; set; }
        public decimal ImporteFinalPesos { get; set; }
        public Nullable<decimal> ImporteFinalDolares { get; set; }
        public decimal ImporteFinalCheques { get; set; }
        public decimal ImporteFinalTarjetas { get; set; }
        public decimal ImporteFinalDepositos { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caja> Caja { get; set; }
    }
}
