//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraIvaVista
    {
        public int Expr4 { get; set; }
        public Nullable<int> IdTipoComprobante { get; set; }
        public int PuntoVenta { get; set; }
        public string NumeroFactura { get; set; }
        public string AuxiliarNumero { get; set; }
        public System.DateTime NumeroEmpresa { get; set; }
        public decimal Empesa { get; set; }
        public decimal Fecha { get; set; }
        public decimal Total { get; set; }
        public decimal Iva { get; set; }
        public decimal IvaAri { get; set; }
        public decimal IvaRes { get; set; }
        public decimal TotalIva { get; set; }
        public string Gasto { get; set; }
        public decimal Neto { get; set; }
        public string Especial { get; set; }
        public string Res { get; set; }
        public decimal IdTipoIva { get; set; }
        public string TipoFactura { get; set; }
        public decimal ResDgr { get; set; }
        public string Cuit { get; set; }
        public string dolar { get; set; }
        public string Diferencia { get; set; }
        public string Clase { get; set; }
        public string NombreEmple { get; set; }
        public int Periodo { get; set; }
        public decimal AbreviaturaFactura { get; set; }
        public int IdTipoMoneda { get; set; }
        public string Isib { get; set; }
        public decimal IdDiario { get; set; }
        public int Cae { get; set; }
        public Nullable<decimal> Impint { get; set; }
        public Nullable<decimal> IdImputacion { get; set; }
        public Nullable<decimal> Tnogra { get; set; }
        public Nullable<decimal> Texento { get; set; }
        public Nullable<decimal> PerGeneral { get; set; }
        public Nullable<decimal> Perib { get; set; }
        public Nullable<decimal> PerMun { get; set; }
        public Nullable<decimal> OtrosImpuestos { get; set; }
        public Nullable<decimal> Tnocat { get; set; }
        public Nullable<decimal> Pernac { get; set; }
        public Nullable<decimal> Iva27 { get; set; }
        public Nullable<decimal> Iva21 { get; set; }
        public Nullable<decimal> Iva105 { get; set; }
        public Nullable<decimal> Ivan5 { get; set; }
        public Nullable<decimal> Iva25 { get; set; }
        public Nullable<decimal> Total21 { get; set; }
        public Nullable<decimal> Total27 { get; set; }
        public Nullable<bool> Total105 { get; set; }
        public Nullable<int> Total5 { get; set; }
        public Nullable<System.DateTime> Activo { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> Expr3 { get; set; }
    }
}
