//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCorriente
    {
        public int ProveedorCodigo { get; set; }
        public string ProveedorNombre { get; set; }
        public Nullable<decimal> MontoPesos { get; set; }
        public Nullable<decimal> MontoDolares { get; set; }
        public Nullable<decimal> TotalDeuda { get; set; }
        public Nullable<System.DateTime> UltimoMovimiento { get; set; }
    }
}
