//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dto
    {
        public int Id { get; set; }
        public int Periodo { get; set; }
        public string CodDto { get; set; }
        public string CodArt { get; set; }
        public string NomDto { get; set; }
        public Nullable<decimal> Loc01 { get; set; }
        public Nullable<decimal> Loc02 { get; set; }
        public Nullable<decimal> Loc03 { get; set; }
        public Nullable<decimal> Loc04 { get; set; }
        public Nullable<decimal> Loc05 { get; set; }
        public Nullable<decimal> Loc06 { get; set; }
        public Nullable<decimal> Loc07 { get; set; }
        public Nullable<decimal> Loc08 { get; set; }
        public Nullable<decimal> Loc09 { get; set; }
        public Nullable<decimal> Loc10 { get; set; }
        public Nullable<decimal> Loc11 { get; set; }
        public Nullable<decimal> Loc12 { get; set; }
        public Nullable<decimal> Ext01 { get; set; }
        public Nullable<decimal> Ext02 { get; set; }
        public Nullable<decimal> Ext03 { get; set; }
        public Nullable<decimal> Ext04 { get; set; }
        public Nullable<decimal> Ext05 { get; set; }
        public Nullable<decimal> Ext06 { get; set; }
        public Nullable<decimal> Ext07 { get; set; }
        public Nullable<decimal> Ext08 { get; set; }
        public Nullable<decimal> Ext09 { get; set; }
        public Nullable<decimal> Ext10 { get; set; }
        public Nullable<decimal> Ext11 { get; set; }
        public Nullable<decimal> Ext12 { get; set; }
        public Nullable<decimal> Epe01 { get; set; }
        public Nullable<decimal> Epe02 { get; set; }
        public Nullable<decimal> Epe03 { get; set; }
        public Nullable<decimal> Epe4 { get; set; }
        public Nullable<decimal> Epe05 { get; set; }
        public Nullable<decimal> Epe06 { get; set; }
        public Nullable<decimal> Epe07 { get; set; }
        public Nullable<decimal> Epe08 { get; set; }
        public Nullable<decimal> Epe09 { get; set; }
        public Nullable<decimal> Epe10 { get; set; }
        public Nullable<decimal> Epe11 { get; set; }
        public Nullable<decimal> Epe12 { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
    }
}
