//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.Contacto = new HashSet<Contacto>();
        }
    
        public int Id { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.TimeSpan> HoraInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public Nullable<int> IdPrioridad { get; set; }
        public Nullable<bool> TodoElDia { get; set; }
        public string Asisten { get; set; }
        public string Recibido { get; set; }
        public string Enviado { get; set; }
        public string Pasado { get; set; }
        public string Ubicacion { get; set; }
        public string Organizador { get; set; }
        public string Obs { get; set; }
        public bool Activo { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contacto { get; set; }
    }
}
