//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemImpre
    {
        public int Id { get; set; }
        public Nullable<int> IdTipoComprobante { get; set; }
        public string PuntoVenta { get; set; }
        public Nullable<int> Factura { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public string Unidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> AuxiliarNumero { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
        public Nullable<int> IdFactVenta { get; set; }
    
        public virtual FactVenta FactVenta { get; set; }
    }
}
