//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuSidebar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuSidebar()
        {
            this.MenuSidebar1 = new HashSet<MenuSidebar>();
        }
    
        public int IdMenuSidebar { get; set; }
        public string Icono { get; set; }
        public string Url { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> IdParent { get; set; }
        public Nullable<int> IdAccion { get; set; }
        public Nullable<int> Orden { get; set; }
        public bool Activo { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Accion Accion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuSidebar> MenuSidebar1 { get; set; }
        public virtual MenuSidebar MenuSidebar2 { get; set; }
    }
}
