//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO
    {
        public int identificador { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public string usuario { get; set; }
        public string evento { get; set; }
        public string instruccion { get; set; }
        public string contexto { get; set; }
    }
}
