//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaOperacion
    {
        public int Id { get; set; }
        public int IdTarjeta { get; set; }
        public int IdGrupoCaja { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Conciliacion { get; set; }
        public string NumeroPago { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
    
        public virtual Tarjetas Tarjetas { get; set; }
    }
}
