//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdRol { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> Creado { get; set; }
        public Nullable<System.DateTime> Actualizado { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
